# Generated by Django 4.1.5 on 2023-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
