# Generated by Django 4.1.5 on 2023-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_address_student_age_student_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='normalized_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
